[colors]
background = '#181818'
foreground = '#d5d0c9'
selection-background = '#383838'
selection-foreground = '#d7c3ba'
cursor = '#e5a1a3'
black = '#000000'
red = '#f56e7f'
green = '#bec975'
yellow = '#f58669'
blue = '#42d9c5'
magenta = '#d286b7'
cyan = '#37cb8a'
white = '#88847f'
light_black = '#2e2a27'
light_red = '#e5a1a3'
light_green = '#e8d6a7'
light_yellow = '#f3b061'
light_blue = '#80c5de'
light_magenta = '#c3a6cb'
light_cyan = '#9ed7a8'
light_white = '#d7c3ba'
