# cutiepro
[colors]
foreground = "#d5d0c9"
background = "#181818"
cursor_bg = "#e5a1a3"
cursor_border = "#e5a1a3"
cursor_fg = "#181818"
selection_bg = "#383838"
selection_fg = "#d7c3ba"

ansi = ["#000000", "#f56e7f", "#bec975", "#f58669", "#42d9c5", "#d286b7", "#37cb8a", "#88847f"]
brights = ["#2e2a27", "#e5a1a3", "#e8d6a7", "#f3b061", "#80c5de", "#c3a6cb", "#9ed7a8", "#d7c3ba"]
