# Colors (cutiepro)

[colors.bright]
black = '#2e2a27'
blue = '#80c5de'
cyan = '#9ed7a8'
green = '#e8d6a7'
magenta = '#c3a6cb'
red = '#e5a1a3'
white = '#d7c3ba'
yellow = '#f3b061'

[colors.cursor]
cursor = '#e5a1a3'
text = '#181818'

[colors.normal]
black = '#000000'
blue = '#42d9c5'
cyan = '#37cb8a'
green = '#bec975'
magenta = '#d286b7'
red = '#f56e7f'
white = '#88847f'
yellow = '#f58669'

[colors.primary]
background = '#181818'
foreground = '#d5d0c9'

[colors.selection]
background = '#383838'
text = '#d7c3ba'
